# Generated by Django 3.0.6 on 2020-05-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
        ('flights', '0002_auto_20180325_0425'),
    ]

    operations = [
    ]
